services:
  photon:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHOTON_VERSION=${PHOTON_VERSION}
    environment:
      - AUTO_UPDATE_INDEX=false
    volumes:
      - photon_data:/app/photon_data
    restart: unless-stopped
    ports:
      - "2322:2322"
volumes:
  photon_data:
