services:
    photon:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PHOTON_VERSION=0.6.1
        environment:
            - UPDATE_STRATEGY=SEQUENTIAL
            - UPDATE_INTERVAL=24h
            - COUNTRY_CODE=zw

        volumes:
            - photon_data:/photon
        restart: unless-stopped
        ports:
            - "2322:2322"
volumes:
    photon_data:
