services:
    photon:
        image: rtuszik/photon-docker:latest
        container_name: "photon-docker"

        environment:
            - UPDATE_STRATEGY=SEQUENTIAL
            - UPDATE_INTERVAL=24h
            # - COUNTRY_CODE=zw
        volumes:
            - photon_data:/photon/app/photon_data
            - photon_temp:/photon/app/temp
        restart: unless-stopped
        ports:
            - "2322:2322"
volumes:
    photon_data:
    photon_temp:
