services:
  photon:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: local/photon:latest
    environment:
      - UPDATE_STRATEGY=PARALLEL
      - UPDATE_INTERVAL=24h
      - LOG_LEVEL=INFO # Options: DEBUG, INFO, ERROR
      # - COUNTRY_CODE=fr
    volumes:
      - photon_data:/photon/photon_data
    restart: unless-stopped
    ports:
      - "2322:2322"
      - "9200:9200"
volumes:
  photon_data:
