services:
    photon:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PHOTON_VERSION=${PHOTON_VERSION}
        environment:
            - UPDATE_STRATEGY=PARALLEL
            - UPDATE_INTERVAL=1d
            - LOG_LEVEL=DEBUG
            # - FORCE_UPDATE=TRUE
            # - COUNTRY_CODE=zw
            # - BASE_URL=https://download1.graphhopper.com/public
        volumes:
            - photon_data:/photon/photon_data
        restart: unless-stopped
        ports:
            - "2322:2322"
volumes:
    photon_data:
