services:
    photon:
        image: rtuszik/photon-docker:latest
        container_name: "photon-docker"
        environment:
            - UPDATE_STRATEGY=PARALLEL
            - UPDATE_INTERVAL=24h
            - LOG_LEVEL=INFO # Options: DEBUG, INFO, ERROR
            # - FORCE_UPDATE=TRUE
            # - COUNTRY_CODE=zw
            # - BASE_URL=https://download1.graphhopper.com/public
        volumes:
            - photon_data:/photon/photon_data
        restart: unless-stopped
        ports:
            - "2322:2322"
volumes:
    photon_data:
